#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

# Setup PHP with safe defaults
agent.set_env("PHP_MEMORYLIMIT", "512M")
agent.set_env("PHP_UPLOADLIMIT", "256M")
agent.set_env("PHP_TIMEZONE", "UTC")
