#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import agent

# test if the secrets.env is not present
if not os.path.exists("secrets.env"):
    # if not present, create it
    passwords = {
        "DOKUWIKI_PASSWORD": os.environ["DOKUWIKI_PASSWORD"],
    }
    agent.write_envfile("secrets.env", passwords)
    agent.unset_env("DOKUWIKI_PASSWORD")
